<?php
/**
 * Classe Employee - Gestione dipendenti
 * PAManager - Comune
 */

class Employee
{
    /**
     * Ottiene un dipendente per ID
     */
    public static function getById(int $id): ?array
    {
        return Database::fetchOne(
            "SELECT e.*, u.name as created_by_name, d.name as department_name, d.code as department_code
             FROM employees e
             LEFT JOIN users u ON e.created_by = u.id
             LEFT JOIN departments d ON e.department_id = d.id
             WHERE e.id = ?",
            [$id]
        );
    }

    /**
     * Verifica che il dipendente appartenga alla company corrente del caller.
     */
    private static function inCurrentTenant(array $employee): bool
    {
        if (!class_exists('Tenant')) return true;
        $cid = Tenant::currentCompanyId();
        return (int) ($employee['company_id'] ?? 0) === (int) $cid;
    }

    /**
     * Ottiene un dipendente per username
     */
    public static function getByUsername(string $username): ?array
    {
        return Database::fetchOne(
            "SELECT * FROM employees WHERE username = ?",
            [$username]
        );
    }

    /**
     * Ottiene un dipendente per codice fiscale
     */
    public static function getByFiscalCode(string $fiscalCode): ?array
    {
        return Database::fetchOne(
            "SELECT * FROM employees WHERE fiscal_code = ?",
            [strtoupper($fiscalCode)]
        );
    }

    /**
     * Lista tutti i dipendenti
     */
    public static function getAll(bool $activeOnly = true, string $search = ''): array
    {
        $cid = class_exists('Tenant') ? Tenant::currentCompanyId() : 1;
        $sql = "SELECT e.*, d.name as department_name, d.code as department_code,
                       (SELECT COUNT(*) FROM documents doc WHERE doc.employee_id = e.id) as document_count
                FROM employees e
                LEFT JOIN departments d ON e.department_id = d.id
                WHERE e.company_id = ?";
        $params = [$cid];

        if ($activeOnly) {
            $sql .= " AND e.is_active = TRUE";
        }

        if (!empty($search)) {
            $sql .= " AND (e.fiscal_code LIKE ? OR e.first_name LIKE ? OR e.last_name LIKE ? OR e.email LIKE ? OR e.username LIKE ?)";
            $searchTerm = "%{$search}%";
            $params = array_merge($params, [$searchTerm, $searchTerm, $searchTerm, $searchTerm, $searchTerm]);
        }

        $sql .= " ORDER BY e.last_name ASC, e.first_name ASC";

        return Database::fetchAll($sql, $params);
    }

    /**
     * Conta dipendenti
     */
    public static function count(bool $activeOnly = true): int
    {
        $cid = class_exists('Tenant') ? Tenant::currentCompanyId() : 1;
        $where = 'company_id = ?' . ($activeOnly ? ' AND is_active = TRUE' : '');
        return Database::count('employees', $where, [$cid]);
    }

    /**
     * Crea un nuovo dipendente
     */
    public static function create(array $data): array
    {
        // Validazione username
        if (empty($data['username']) || strlen($data['username']) < 3) {
            return ['success' => false, 'error' => 'Username deve avere almeno 3 caratteri'];
        }

        if (!preg_match('/^[a-zA-Z0-9_\.]+$/', $data['username'])) {
            return ['success' => false, 'error' => 'Username può contenere solo lettere, numeri, underscore e punti'];
        }

        // Generazione automatica password se non fornita
        if (empty($data['password'])) {
            $data['password'] = Auth::generateSecurePassword(14);
            $autoGenerated = true;
        } else {
            $autoGenerated = false;
            if (strlen($data['password']) < 8) {
                return ['success' => false, 'error' => 'Password deve avere almeno 8 caratteri'];
            }
            if (!self::validatePasswordStrength($data['password'])) {
                return ['success' => false, 'error' => 'Password troppo debole. Deve contenere almeno una maiuscola, una minuscola, un numero e un carattere speciale.'];
            }
        }

        // Validazione codice fiscale
        if (empty($data['fiscal_code']) || !self::validateFiscalCode($data['fiscal_code'])) {
            return ['success' => false, 'error' => 'Codice fiscale non valido'];
        }

        if (empty($data['first_name'])) {
            return ['success' => false, 'error' => 'Nome obbligatorio'];
        }

        if (empty($data['last_name'])) {
            return ['success' => false, 'error' => 'Cognome obbligatorio'];
        }

        // Validazione reparto obbligatorio
        if (empty($data['department_id'])) {
            return ['success' => false, 'error' => 'Reparto obbligatorio'];
        }

        // Verifica che il reparto esista e sia attivo
        if (!Database::exists('departments', 'id = ? AND is_active = TRUE', [$data['department_id']])) {
            return ['success' => false, 'error' => 'Reparto non valido o non attivo'];
        }

        $cid = class_exists('Tenant') ? Tenant::currentCompanyId() : 1;

        // Verifica username unico nella stessa azienda
        if (Database::exists('employees', 'username = ? AND company_id = ?', [$data['username'], $cid])) {
            return ['success' => false, 'error' => 'Username gia esistente in questa azienda'];
        }

        // Verifica codice fiscale unico nella stessa azienda
        $fiscalCode = strtoupper(trim($data['fiscal_code']));
        if (Database::exists('employees', 'fiscal_code = ? AND company_id = ?', [$fiscalCode, $cid])) {
            return ['success' => false, 'error' => 'Codice fiscale gia registrato in questa azienda'];
        }

        // Validazione email (obbligatoria per invio credenziali)
        if (empty($data['email'])) {
            return ['success' => false, 'error' => 'Email obbligatoria: necessaria per inviare le credenziali al dipendente'];
        }
        if (!filter_var($data['email'], FILTER_VALIDATE_EMAIL)) {
            return ['success' => false, 'error' => 'Email non valida'];
        }

        $user = Auth::getUser();

        $nullIfEmpty = static fn($v) => ($v === '' || $v === null) ? null : $v;

        try {
            $toFloat = static function($v) {
                if ($v === '' || $v === null) return null;
                return (float) str_replace(',', '.', (string)$v);
            };
            $id = Database::insert('employees', [
                'company_id' => class_exists('Tenant') ? Tenant::currentCompanyId() : 1,
                'username' => $data['username'],
                'password_hash' => password_hash($data['password'], PASSWORD_BCRYPT, ['cost' => PASSWORD_COST]),
                'fiscal_code' => $fiscalCode,
                'first_name' => trim($data['first_name']),
                'last_name' => trim($data['last_name']),
                'email' => $nullIfEmpty($data['email'] ?? null),
                'phone' => $nullIfEmpty($data['phone'] ?? null),
                'department_id' => $nullIfEmpty($data['department_id'] ?? null),
                'position' => $nullIfEmpty($data['position'] ?? null),
                'hire_date' => $nullIfEmpty($data['hire_date'] ?? null),
                // Dati personali ed economici (migration 013)
                'address'        => $nullIfEmpty($data['address'] ?? null),
                'birth_date'     => $nullIfEmpty($data['birth_date'] ?? null),
                'job_level'      => $nullIfEmpty($data['job_level'] ?? null),
                'ral_amount'     => $toFloat($data['ral_amount'] ?? null),
                'monthly_salary' => $toFloat($data['monthly_salary'] ?? null),
                'iban'           => $nullIfEmpty(isset($data['iban']) && $data['iban'] !== '' ? strtoupper(preg_replace('/\s+/', '', $data['iban'])) : null),
                'ccnl_id'                => $nullIfEmpty($data['ccnl_id'] ?? null),
                'ferie_year_override'    => $toFloat($data['ferie_year_override'] ?? null),
                'permessi_year_override' => $toFloat($data['permessi_year_override'] ?? null),
                // Orario personalizzato (migration 025): null = default azienda
                'working_days'   => $nullIfEmpty($data['working_days'] ?? null),
                'hours_per_day'  => $toFloat($data['hours_per_day'] ?? null),
                // Smart working + buoni pasto (migration 047/048): null = eredita azienda, '' = nessun giorno
                'smart_working_days'               => $data['smart_working_days'] ?? null,
                'buoni_pasto_min_hours_override'   => $toFloat($data['buoni_pasto_min_hours_override'] ?? null),
                'buoni_pasto_sw_eligible_override' => isset($data['buoni_pasto_sw_eligible_override']) && $data['buoni_pasto_sw_eligible_override'] !== null && $data['buoni_pasto_sw_eligible_override'] !== '' ? (int) $data['buoni_pasto_sw_eligible_override'] : null,
                'buoni_pasto_excluded'             => !empty($data['buoni_pasto_excluded']) ? 1 : 0,
                'is_active' => 1,
                'must_change_password' => 1,
                'created_by' => $user ? $user['id'] : null
            ]);

            // Crea directory per documenti
            self::createDocumentDirectory($id);

            self::logAction('employee_created', $id, null, [
                'username' => $data['username'],
                'fiscal_code' => $fiscalCode,
                'name' => $data['first_name'] . ' ' . $data['last_name']
            ]);

            // Invio email di benvenuto con credenziali temporanee
            $emailSent = false;
            $emailError = null;
            if (class_exists('Mailer') && Mailer::isConfigured()) {
                $loginUrl = function_exists('buildPublicUrl')
                    ? buildPublicUrl('/auth/login.php')
                    : (defined('PUBLIC_URL') ? PUBLIC_URL . '/auth/login.php' : '/auth/login.php');
                $fullName = trim($data['first_name'] . ' ' . $data['last_name']);
                $usernameSafe = htmlspecialchars($data['username']);
                $passwordSafe = htmlspecialchars($data['password']);
                $nameSafe = htmlspecialchars($fullName);

                $html = "<p>Ciao {$nameSafe},</p>"
                      . "<p>È stato creato un account per te su Connecteed HR. Queste sono le tue credenziali temporanee di accesso:</p>"
                      . "<ul>"
                      . "<li><strong>Username:</strong> {$usernameSafe}</li>"
                      . "<li><strong>Password temporanea:</strong> <code>{$passwordSafe}</code></li>"
                      . "</ul>"
                      . "<p><a href=\"{$loginUrl}\">Accedi al portale</a></p>"
                      . "<p>Al primo accesso ti verrà richiesto di impostare una nuova password personale.</p>"
                      . "<p>Per motivi di sicurezza non condividere queste credenziali con altre persone.</p>";
                $text = "Ciao {$fullName},\n\n"
                      . "È stato creato un account per te su Connecteed HR.\n\n"
                      . "Username: {$data['username']}\n"
                      . "Password temporanea: {$data['password']}\n\n"
                      . "Login: {$loginUrl}\n\n"
                      . "Al primo accesso ti verrà richiesto di impostare una nuova password.";

                $emailSent = Mailer::send($data['email'], $fullName, 'Le tue credenziali di accesso Connecteed HR', $html, $text);
                if (!$emailSent) {
                    $emailError = Mailer::getLastError();
                }
            } else {
                $emailError = 'SMTP non configurato';
            }

            return [
                'success'        => true,
                'id'             => $id,
                'temp_password'  => $autoGenerated ? $data['password'] : null,
                'email_sent'     => $emailSent,
                'email_error'    => $emailError
            ];
        } catch (Exception $e) {
            return ['success' => false, 'error' => 'Errore durante la creazione del dipendente: ' . $e->getMessage()];
        }
    }

    /**
     * Aggiorna un dipendente
     */
    public static function update(int $id, array $data): array
    {
        $employee = self::getById($id);
        if (!$employee) {
            return ['success' => false, 'error' => 'Dipendente non trovato'];
        }
        if (!self::inCurrentTenant($employee)) {
            return ['success' => false, 'error' => 'Dipendente non appartiene all\'azienda corrente'];
        }

        $updateData = [];

        // Username modificabile solo se diverso
        if (isset($data['username']) && $data['username'] !== $employee['username']) {
            if (strlen($data['username']) < 3) {
                return ['success' => false, 'error' => 'Username deve avere almeno 3 caratteri'];
            }
            if (!preg_match('/^[a-zA-Z0-9_\.]+$/', $data['username'])) {
                return ['success' => false, 'error' => 'Username può contenere solo lettere, numeri, underscore e punti'];
            }
            if (Database::exists('employees', 'username = ? AND company_id = ? AND id != ?', [$data['username'], (int)$employee['company_id'], $id])) {
                return ['success' => false, 'error' => 'Username gia esistente in questa azienda'];
            }
            $updateData['username'] = $data['username'];
        }

        // Codice fiscale modificabile solo se diverso
        if (isset($data['fiscal_code'])) {
            $fiscalCode = strtoupper(trim($data['fiscal_code']));
            if ($fiscalCode !== $employee['fiscal_code']) {
                if (!self::validateFiscalCode($fiscalCode)) {
                    return ['success' => false, 'error' => 'Codice fiscale non valido'];
                }
                if (Database::exists('employees', 'fiscal_code = ? AND company_id = ? AND id != ?', [$fiscalCode, (int)$employee['company_id'], $id])) {
                    return ['success' => false, 'error' => 'Codice fiscale gia registrato in questa azienda'];
                }
                $updateData['fiscal_code'] = $fiscalCode;
            }
        }

        if (isset($data['first_name']) && !empty($data['first_name'])) {
            $updateData['first_name'] = trim($data['first_name']);
        }

        if (isset($data['last_name']) && !empty($data['last_name'])) {
            $updateData['last_name'] = trim($data['last_name']);
        }

        if (isset($data['email'])) {
            if (!empty($data['email']) && !filter_var($data['email'], FILTER_VALIDATE_EMAIL)) {
                return ['success' => false, 'error' => 'Email non valida'];
            }
            $updateData['email'] = $data['email'] ?: null;
        }

        if (isset($data['phone'])) {
            $updateData['phone'] = $data['phone'] ?: null;
        }

        if (array_key_exists('department_id', $data)) {
            $updateData['department_id'] = $data['department_id'] ?: null;
        }

        if (isset($data['position'])) {
            $updateData['position'] = $data['position'] ?: null;
        }

        if (isset($data['hire_date'])) {
            $updateData['hire_date'] = $data['hire_date'] ?: null;
        }

        // Nuovi campi (migration 013) — non validati strict, salvati cosi come sono
        if (array_key_exists('address', $data))        $updateData['address']        = $data['address'] ?: null;
        if (array_key_exists('birth_date', $data))     $updateData['birth_date']     = $data['birth_date'] ?: null;
        if (array_key_exists('job_level', $data))      $updateData['job_level']      = $data['job_level'] ?: null;
        if (array_key_exists('ral_amount', $data)) {
            $updateData['ral_amount'] = $data['ral_amount'] !== '' && $data['ral_amount'] !== null
                ? (float)str_replace(',', '.', (string)$data['ral_amount']) : null;
        }
        if (array_key_exists('monthly_salary', $data)) {
            $updateData['monthly_salary'] = $data['monthly_salary'] !== '' && $data['monthly_salary'] !== null
                ? (float)str_replace(',', '.', (string)$data['monthly_salary']) : null;
        }
        if (array_key_exists('iban', $data))           $updateData['iban']           = $data['iban'] ? strtoupper(preg_replace('/\s+/', '', $data['iban'])) : null;

        // UID badge NFC per apertura porta (migration 038)
        if (array_key_exists('nfc_uid', $data)) {
            $__uid = strtoupper(preg_replace('/[^0-9A-Fa-f]/', '', (string) $data['nfc_uid']));
            $updateData['nfc_uid'] = $__uid !== '' ? $__uid : null;
        }

        // Orario di lavoro (migration 025): null = usa default azienda, '' = nessun giorno
        if (array_key_exists('working_days', $data)) {
            $updateData['working_days'] = $data['working_days'];
        }
        if (array_key_exists('hours_per_day', $data)) {
            $updateData['hours_per_day'] = $data['hours_per_day'];
        }

        // Smart working + buoni pasto (migration 047/048): null = eredita azienda, '' = nessun giorno SW
        if (array_key_exists('smart_working_days', $data)) {
            $updateData['smart_working_days'] = $data['smart_working_days'];
        }
        if (array_key_exists('buoni_pasto_min_hours_override', $data)) {
            $updateData['buoni_pasto_min_hours_override'] = $data['buoni_pasto_min_hours_override'];
        }
        if (array_key_exists('buoni_pasto_sw_eligible_override', $data)) {
            $updateData['buoni_pasto_sw_eligible_override'] = $data['buoni_pasto_sw_eligible_override'];
        }
        if (array_key_exists('buoni_pasto_excluded', $data)) {
            $updateData['buoni_pasto_excluded'] = ((bool) $data['buoni_pasto_excluded']) ? 1 : 0;
        }

        // CCNL e override saldi (migration 033)
        if (array_key_exists('ccnl_id', $data)) {
            $updateData['ccnl_id'] = $data['ccnl_id'] ?: null;
        }
        if (array_key_exists('ferie_year_override', $data)) {
            $updateData['ferie_year_override'] = $data['ferie_year_override'];
        }
        if (array_key_exists('permessi_year_override', $data)) {
            $updateData['permessi_year_override'] = $data['permessi_year_override'];
        }

        if (isset($data['is_active'])) {
            // MySQL TINYINT(1) in strict mode rifiuta i valori boolean PHP false (li converte in '');
            // forziamo int 0/1 per affidabilita.
            $updateData['is_active'] = ((bool) $data['is_active']) ? 1 : 0;
        }

        if (empty($updateData)) {
            return ['success' => false, 'error' => 'Nessun dato da aggiornare'];
        }

        try {
            Database::update('employees', $updateData, 'id = ?', [$id]);
            self::logAction('employee_updated', $id, $employee, $updateData);
            return ['success' => true];
        } catch (Throwable $e) {
            error_log('[Employee::update] id=' . $id . ' fields=' . implode(',', array_keys($updateData)) . ' err=' . $e->getMessage());
            return ['success' => false, 'error' => 'Errore aggiornamento: ' . $e->getMessage()];
        }
    }

    /**
     * Elimina un dipendente
     */
    public static function delete(int $id): array
    {
        $employee = self::getById($id);
        if (!$employee) {
            return ['success' => false, 'error' => 'Dipendente non trovato'];
        }
        if (!self::inCurrentTenant($employee)) {
            return ['success' => false, 'error' => 'Dipendente non appartiene all\'azienda corrente'];
        }

        try {
            // I documenti vengono eliminati automaticamente (ON DELETE CASCADE)
            Database::delete('employees', 'id = ?', [$id]);

            // Elimina directory documenti
            self::deleteDocumentDirectory($id);

            self::logAction('employee_deleted', $id, $employee, null);
            return ['success' => true];
        } catch (Exception $e) {
            return ['success' => false, 'error' => 'Errore durante l\'eliminazione: ' . $e->getMessage()];
        }
    }

    /**
     * Disattiva un dipendente
     */
    public static function deactivate(int $id): array
    {
        return self::update($id, ['is_active' => 0]);
    }

    /**
     * Riattiva un dipendente
     */
    public static function activate(int $id): array
    {
        return self::update($id, ['is_active' => 1]);
    }

    /**
     * Reset password dipendente (genera nuova password)
     */
    public static function resetPassword(int $id): array
    {
        $employee = self::getById($id);
        if (!$employee) {
            return ['success' => false, 'error' => 'Dipendente non trovato'];
        }

        $newPassword = self::generatePassword();
        $hash = password_hash($newPassword, PASSWORD_BCRYPT, ['cost' => PASSWORD_COST]);

        try {
            Database::update('employees', [
                'password_hash' => $hash,
                'failed_attempts' => 0,
                'locked_until' => null
            ], 'id = ?', [$id]);

            self::logAction('password_reset', $id, null, null);

            return ['success' => true, 'password' => $newPassword];
        } catch (Exception $e) {
            return ['success' => false, 'error' => 'Errore durante il reset password'];
        }
    }

    /**
     * Valida la forza della password
     */
    private static function validatePasswordStrength(string $password): bool
    {
        // Almeno 8 caratteri, 1 maiuscola, 1 minuscola, 1 numero, 1 speciale
        return preg_match('/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).{8,}$/', $password) === 1;
    }

    /**
     * Genera una password sicura
     */
    private static function generatePassword(int $length = 12): string
    {
        $upper = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $lower = 'abcdefghijklmnopqrstuvwxyz';
        $numbers = '0123456789';
        $special = '!@#$%^&*()_+-=';

        $password = $upper[random_int(0, strlen($upper) - 1)];
        $password .= $lower[random_int(0, strlen($lower) - 1)];
        $password .= $numbers[random_int(0, strlen($numbers) - 1)];
        $password .= $special[random_int(0, strlen($special) - 1)];

        $all = $upper . $lower . $numbers . $special;
        for ($i = 4; $i < $length; $i++) {
            $password .= $all[random_int(0, strlen($all) - 1)];
        }

        return str_shuffle($password);
    }

    /**
     * Valida formato codice fiscale italiano
     */
    public static function validateFiscalCode(string $fiscalCode): bool
    {
        $fiscalCode = strtoupper(trim($fiscalCode));

        // Verifica lunghezza e formato base
        if (strlen($fiscalCode) !== 16) {
            return false;
        }

        // Pattern codice fiscale: 6 lettere + 2 numeri + 1 lettera + 2 numeri + 1 lettera + 3 alfanumerici + 1 lettera
        $pattern = '/^[A-Z]{6}[0-9]{2}[A-Z][0-9]{2}[A-Z][0-9]{3}[A-Z]$/';

        if (!preg_match($pattern, $fiscalCode)) {
            return false;
        }

        // Verifica carattere di controllo
        return self::verifyFiscalCodeChecksum($fiscalCode);
    }

    /**
     * Verifica checksum codice fiscale
     */
    private static function verifyFiscalCodeChecksum(string $cf): bool
    {
        $odd = [
            '0' => 1, '1' => 0, '2' => 5, '3' => 7, '4' => 9, '5' => 13, '6' => 15, '7' => 17, '8' => 19, '9' => 21,
            'A' => 1, 'B' => 0, 'C' => 5, 'D' => 7, 'E' => 9, 'F' => 13, 'G' => 15, 'H' => 17, 'I' => 19, 'J' => 21,
            'K' => 2, 'L' => 4, 'M' => 18, 'N' => 20, 'O' => 11, 'P' => 3, 'Q' => 6, 'R' => 8, 'S' => 12, 'T' => 14,
            'U' => 16, 'V' => 10, 'W' => 22, 'X' => 25, 'Y' => 24, 'Z' => 23
        ];

        $even = [
            '0' => 0, '1' => 1, '2' => 2, '3' => 3, '4' => 4, '5' => 5, '6' => 6, '7' => 7, '8' => 8, '9' => 9,
            'A' => 0, 'B' => 1, 'C' => 2, 'D' => 3, 'E' => 4, 'F' => 5, 'G' => 6, 'H' => 7, 'I' => 8, 'J' => 9,
            'K' => 10, 'L' => 11, 'M' => 12, 'N' => 13, 'O' => 14, 'P' => 15, 'Q' => 16, 'R' => 17, 'S' => 18, 'T' => 19,
            'U' => 20, 'V' => 21, 'W' => 22, 'X' => 23, 'Y' => 24, 'Z' => 25
        ];

        $sum = 0;
        for ($i = 0; $i < 15; $i++) {
            $char = $cf[$i];
            $sum += ($i % 2 === 0) ? $odd[$char] : $even[$char];
        }

        $checkChar = chr(65 + ($sum % 26));
        return $cf[15] === $checkChar;
    }

    /**
     * Crea directory per documenti dipendente
     */
    private static function createDocumentDirectory(int $employeeId): void
    {
        $path = DOCUMENTS_PATH . '/' . $employeeId;
        if (!is_dir($path)) {
            mkdir($path, 0755, true);
        }
    }

    /**
     * Elimina directory documenti dipendente
     */
    private static function deleteDocumentDirectory(int $employeeId): void
    {
        $path = DOCUMENTS_PATH . '/' . $employeeId;
        if (is_dir($path)) {
            self::deleteDirectory($path);
        }
    }

    /**
     * Elimina directory ricorsivamente
     */
    private static function deleteDirectory(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }

        $files = array_diff(scandir($dir), ['.', '..']);
        foreach ($files as $file) {
            $path = $dir . '/' . $file;
            is_dir($path) ? self::deleteDirectory($path) : unlink($path);
        }
        rmdir($dir);
    }

    /**
     * Log azioni
     */
    private static function logAction(string $action, int $entityId, ?array $oldValues, ?array $newValues): void
    {
        $user = Auth::getUser();
        if ($user) {
            try {
                Database::insert('audit_log', [
                    'user_type' => $user['role'],
                    'user_id' => $user['id'],
                    'action' => $action,
                    'entity_type' => 'employee',
                    'entity_id' => $entityId,
                    'old_values' => $oldValues ? json_encode($oldValues) : null,
                    'new_values' => $newValues ? json_encode($newValues) : null,
                    'ip_address' => $_SERVER['REMOTE_ADDR'] ?? null,
                    'user_agent' => $_SERVER['HTTP_USER_AGENT'] ?? null
                ]);
            } catch (Exception $e) {
                error_log('Audit log failed: ' . $e->getMessage());
            }
        }
    }
}
