-- Migration 018: preferenze notifica per dipendente.
-- Idempotente: usa controlli su INFORMATION_SCHEMA.

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
          WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='employees' AND COLUMN_NAME='notify_email');
SET @sql = IF(@c=0, "ALTER TABLE employees ADD COLUMN notify_email TINYINT(1) NOT NULL DEFAULT 1", 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
          WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='employees' AND COLUMN_NAME='notify_push');
SET @sql = IF(@c=0, "ALTER TABLE employees ADD COLUMN notify_push TINYINT(1) NOT NULL DEFAULT 1", 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @c = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
          WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='employees' AND COLUMN_NAME='email_unsubscribe_token');
SET @sql = IF(@c=0, "ALTER TABLE employees ADD COLUMN email_unsubscribe_token VARCHAR(64) NULL UNIQUE", 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
